language: python
python:
- 3.7
- 3.6
- 3.5
- 3.4
- 2.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: almoore
  password:
    secure: dh2v/uN8VcT0Q/ojUlZSvKGLtSnlFNcK3TRyfImIYXQwvo4XOsYkAgtDACCDRJINQdxP1JQboQ41VR2dBx0KFf3a6u10KhaRcKS7c1H03p2ym1EU4WhaHCY6deAtjOhGF/ZnkSLQu6pAqyJBFZT/uxSQAZGpNY+puDkuTDYPiBxJjACWPgA4fSl/dW1ZCGAq1GJ73l2qMhhTWMXpbRX0dtX7PiLNq2pAcdnGRqJoWsUn2X7nBnfa/U8KeS19R/jMA8ugkBrnt+XY2i6Lrr2+V1wJIj81kyKjYx11IF+PgipITUNNNI6Go7Vl71E0RWevTV93Cst1F29jC1oawZZL0ehijm6a1oyUxnM5fz7lejCHIFhoRa1drjZ2mD0J0qMS9Ck5tvLo8bkaw7zLZolrZ7MVk/SVMr8JRY9gnCWiaUnN7RWB0Tey6VQhQKpgVEeDm2PtMzNRmd2MveBIWIe61LUxq5MxVL3E/j46/MP7mFkq4A5CBc4kWf767plFEf6XnaSrv6nyEBcR6X3jodexTsd1lPMNziPsTj2AZlAth9R61HoPPOiIiia6q5W7hzkd7P1h/rJez3/OXd87Or+z7PpA3vEswtJY3PXu4MCz6PEJLEanmflflRz7MG6nMsHCznuhYyKEty7n4c2p7gVsRuBbbro90ScnDNZBKweUaJM=
  on:
    tags: true
    repo: almoore/ptct
    python: 3.6
